fail_fast: true

repos:
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/"
        entry: pylint -j 4 --source-roots .
      - id: mypy
        name: Local MyPy
        language: system
        types:
          - python
#        files: \.py$
#        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        exclude: "/(site-packages|development-[^/]*|docs|node_modules|__pycache__|\\..*)/$"
        require_serial: true
#        entry: ./basic-installer.bash mypy --strict
        entry: mypy --strict --show-error-codes --no-warn-unused-ignores
# Main problem: python executable path, used to find the environment is hard
#  - repo: https://github.com/pre-commit/mirrors-mypy.git
#    rev: v1.2.0
#    hooks:
#      - id: mypy
#        exclude: "^[^/]*env/|dev-[^/]*/"
#        require_serial: true
#        args: [--strict, --show-error-codes, --no-warn-unused-ignores, --python-executable, .pyWEenv/bin/python]
#  - repo: meta
  - repo: https://github.com/inab/python-extended-json-schema-validator.git
    rev: v0.15.1
    hooks:
#      - id: identity
      - id: jsonschema_dir_validate
        name: Check jsonschema
        types:
          - json
        files: ^wfexs_backend/schemas/.*\.json$
        require_serial: true
        pass_filenames: false
        args: [ wfexs_backend/schemas ]

  - repo: https://github.com/jmfernandez/pre-commit_mirrors-actionlint.git
    rev: v1.6.25
    hooks:
      - id: actionlint

  - repo: https://github.com/ambv/black.git
    rev: 23.3.0
    hooks:
      - id: black
        exclude: "^[^/]*env/|development-[^/]*/|docs/"
        args: [--diff, --check]

  - repo: https://github.com/jmfernandez/citation-cff-checker.git
    rev: v0.1.0
    hooks:
      - id: cff_ver_validate
